# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/yaki_backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directory: "/yaki_mobile"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/yaki_admin_backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/yaki_karate"
    schedule:
      interval: "weekly"
