version: "3.9"
services:
   api:
    build:
      context: ../yaki_backend
      dockerfile: dockerfile
    env_file: .env
    environment:
       DB_HOST: bdd
    ports:
      - "${Port}:3000"
    depends_on:
      - bdd
   bdd:
    env_file: .env
    image: postgres:15.4
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
   admin:
    build:
      context: ../yaki_admin_backend
      dockerfile: dockerfile
    env_file: .env
    environment:
      DB_HOST: bdd
    ports:
      - "8080:8080"
    depends_on:
      - bdd
