// Mocks generated by Mockito 5.3.2 from annotations
// in yaki/test/repositories/declaration_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;
import 'package:yaki/data/models/declaration_model.dart' as _i6;
import 'package:yaki/data/sources/remote/declaration_api.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRequestOptions_1 extends _i1.SmartFake
    implements _i3.RequestOptions {
  _FakeRequestOptions_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHeaders_2 extends _i1.SmartFake implements _i3.Headers {
  _FakeHeaders_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUri_3 extends _i1.SmartFake implements Uri {
  _FakeUri_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_4<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeclarationApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeclarationApi extends _i1.Mock implements _i4.DeclarationApi {
  MockDeclarationApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.HttpResponse<dynamic>> getDeclaration(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeclaration,
          [id],
        ),
        returnValue: _i5.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #getDeclaration,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.HttpResponse<dynamic>>);
  @override
  _i5.Future<_i2.HttpResponse<dynamic>> create(
          _i6.DeclarationModel? declaration) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [declaration],
        ),
        returnValue: _i5.Future<_i2.HttpResponse<dynamic>>.value(
            _FakeHttpResponse_0<dynamic>(
          this,
          Invocation.method(
            #create,
            [declaration],
          ),
        )),
      ) as _i5.Future<_i2.HttpResponse<dynamic>>);
}

/// A class which mocks [Response].
///
/// See the documentation for Mockito's code generation for more information.
class MockResponse<T> extends _i1.Mock implements _i3.Response<T> {
  MockResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set data(T? _data) => super.noSuchMethod(
        Invocation.setter(
          #data,
          _data,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.RequestOptions get requestOptions => (super.noSuchMethod(
        Invocation.getter(#requestOptions),
        returnValue: _FakeRequestOptions_1(
          this,
          Invocation.getter(#requestOptions),
        ),
      ) as _i3.RequestOptions);
  @override
  set requestOptions(_i3.RequestOptions? _requestOptions) => super.noSuchMethod(
        Invocation.setter(
          #requestOptions,
          _requestOptions,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set statusCode(int? _statusCode) => super.noSuchMethod(
        Invocation.setter(
          #statusCode,
          _statusCode,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set statusMessage(String? _statusMessage) => super.noSuchMethod(
        Invocation.setter(
          #statusMessage,
          _statusMessage,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get isRedirect => (super.noSuchMethod(
        Invocation.getter(#isRedirect),
        returnValue: false,
      ) as bool);
  @override
  set isRedirect(bool? _isRedirect) => super.noSuchMethod(
        Invocation.setter(
          #isRedirect,
          _isRedirect,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i3.RedirectRecord> get redirects => (super.noSuchMethod(
        Invocation.getter(#redirects),
        returnValue: <_i3.RedirectRecord>[],
      ) as List<_i3.RedirectRecord>);
  @override
  set redirects(List<_i3.RedirectRecord>? _redirects) => super.noSuchMethod(
        Invocation.setter(
          #redirects,
          _redirects,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<String, dynamic> get extra => (super.noSuchMethod(
        Invocation.getter(#extra),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
  @override
  set extra(Map<String, dynamic>? _extra) => super.noSuchMethod(
        Invocation.setter(
          #extra,
          _extra,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Headers get headers => (super.noSuchMethod(
        Invocation.getter(#headers),
        returnValue: _FakeHeaders_2(
          this,
          Invocation.getter(#headers),
        ),
      ) as _i3.Headers);
  @override
  set headers(_i3.Headers? _headers) => super.noSuchMethod(
        Invocation.setter(
          #headers,
          _headers,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Uri get realUri => (super.noSuchMethod(
        Invocation.getter(#realUri),
        returnValue: _FakeUri_3(
          this,
          Invocation.getter(#realUri),
        ),
      ) as Uri);
}

/// A class which mocks [HttpResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpResponse extends _i1.Mock
    implements _i2.HttpResponse<Map<String, dynamic>> {
  MockHttpResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
  @override
  _i3.Response<dynamic> get response => (super.noSuchMethod(
        Invocation.getter(#response),
        returnValue: _FakeResponse_4<dynamic>(
          this,
          Invocation.getter(#response),
        ),
      ) as _i3.Response<dynamic>);
}

/// A class which mocks [HttpResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpResponseList extends _i1.Mock
    implements _i2.HttpResponse<List<Map<String, dynamic>>> {
  MockHttpResponseList() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: <Map<String, dynamic>>[],
      ) as List<Map<String, dynamic>>);
  @override
  _i3.Response<dynamic> get response => (super.noSuchMethod(
        Invocation.getter(#response),
        returnValue: _FakeResponse_4<dynamic>(
          this,
          Invocation.getter(#response),
        ),
      ) as _i3.Response<dynamic>);
}

/// A class which mocks [HttpResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpResponseString extends _i1.Mock
    implements _i2.HttpResponse<String> {
  MockHttpResponseString() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get data => (super.noSuchMethod(
        Invocation.getter(#data),
        returnValue: '',
      ) as String);
  @override
  _i3.Response<dynamic> get response => (super.noSuchMethod(
        Invocation.getter(#response),
        returnValue: _FakeResponse_4<dynamic>(
          this,
          Invocation.getter(#response),
        ),
      ) as _i3.Response<dynamic>);
}
