FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY . .

RUN npm install

RUN npm run swagger

# Bundle app source
COPY . .

EXPOSE 3000

CMD [ "npm", "start" ]