version: "3.9"
services:
   api:
    build: .
    env_file: .env
    environment:
       DB_HOST: bdd
    ports:
      - "3000:3000"
    depends_on:
      - bdd
   bdd:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"