FROM node:lts-alpine as build
# install simple http server for serving static content
# make the 'app' folder the current working directory
RUN mkdir /app

WORKDIR /app
# copy both 'package.json' and 'package-lock.json' (if available)
COPY ["package.json", "package-lock.json*", "./"]
# install project dependencies
RUN npm install --silent 
RUN npm install -g http-server 
RUN npm install --global npm-run-all

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY .eslintrc.js ./
COPY babel.config.js ./
COPY . .
# build app for production with minification
RUN npm run build


EXPOSE 4173
CMD ["http-server", "dist", "-p", "4173"]
