FROM node:lts-alpine as build
# install simple http server for serving static content
# make the 'app' folder the current working directory
RUN mkdir /app

WORKDIR /app
# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./
# install project dependencies
RUN npm install --silent \
    npm install @vue/cli@4.5.8 -g
# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY .eslintrc.js ./
COPY babel.config.js ./
COPY . .
# build app for production with minification
RUN npm run build

FROM nginx:1.19.6-alpine

COPY --from=build /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 4173
CMD ["nginx", "-g", "daemon off;"]