FROM ubuntu:latest

# Create app working directory
RUN mkdir /app/

WORKDIR /app/*

# Install app dependencies
COPY . .

RUN npm install

# Bundle app source 
COPY . .

EXPOSE 5173

CMD [ "npm", "dev" ]
