FROM ubuntu:latest

# Create app working directory
RUN mkdir /app/
WORKDIR /app/

# Install dependencies
RUN  flutter upgrade
RUN  flutter pub get
RUN  dart format --set-exit-if-changed .
RUN  flutter analyze
RUN  flutter test

EXPOSE 443

# Deploy webserver
FROM nginx:1.21.5

COPY build/web /usr/share/nginx/html