name: Create and publish all Docker images

on:
  push:
    branches: ["main", "chore/published_docker_front_admin"]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: true
        default: "Manual trigger"

jobs:
  build-yaki-backend-mobile:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish Yaki backend Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username phanatic --password-stdin
          cd yaki_backend
          docker build -t yaki_backend .
          docker tag yaki_backend ghcr.io/xpeho/yaki:backend-mobile-latest
          docker push ghcr.io/xpeho/yaki:backend-mobile-latest
  build-yaki-front-mobile:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          java-version: "17.x"
          distribution: "temurin"
      - uses: subosito/flutter-action@v2
      - name: Install lcov
        run: |
          sudo apt update
          sudo apt install lcov
      - name: Build and publish Yaki frontend mobile Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username phanatic --password-stdin
          cd yaki_mobile
          flutter upgrade
          flutter pub get
          dart format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build web --dart-define API_BASE_URL=https://yaki.uat.xpeho.fr/ --dart-define CRED_HASH_PASS=${{ secrets.CRED_HASH_PASS }} --base-href "/api/"
          docker build -t yaki_mobile .
          docker tag yaki_mobile ghcr.io/xpeho/yaki:frontend-mobile-latest
          docker push ghcr.io/xpeho/yaki:frontend-mobile-latest
  build-yaki-backend-admin:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          java-version: "17.x"
          distribution: "temurin"
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "17.x"
          distribution: "temurin"
      - name: Build and publish Yaki backend admin Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username phanatic --password-stdin
          cd yaki_admin_backend
          echo ${{ secrets.APPLICATION_PROPERTIES }} | base64 -d > src/main/resources/application.properties
          gradle clean build
          docker build -t yaki_admin_backend .
          docker tag yaki_admin_backend ghcr.io/xpeho/yaki:backend-admin-latest
          docker push ghcr.io/xpeho/yaki:backend-admin-latest
  build-yaki-frontend-admin:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and publish Yaki frontend admin Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username phanatic --password-stdin
          cd yaki_admin
          npm run build --base-href='/admin-ui/'
          docker build -t yaki_admin .
          docker tag yaki_admin ghcr.io/xpeho/yaki:frontend-admin-latest
          docker push ghcr.io/xpeho/yaki:frontend-admin-latest
