on: pull_request 
name: Test and build
jobs: 
  flutter-mobile:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: yaki_mobile
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: stable
      - name: Install lcov
        run: |
          sudo apt update
          sudo apt install lcov 
      - name: Build apk
        run: |
          flutter upgrade
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test --coverage
          flutter build apk --debug
  flutter-web:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: yaki_mobile
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
           flutter-version: '3.7.3'
      - name: Build web
        run: |
          flutter upgrade
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test --coverage
          flutter build web
  nodejs:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: yaki_backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Build
        run: |
          npm ci
          npm run swagger
          npm run test
          npm run build